name: PR testing of CLI action

on:
  push

jobs:
  should-workflow-run:
    runs-on: ubuntu-latest
    outputs:
      shouldrun: 'true'

  build-docker:
    needs: should-workflow-run
    name: Build Docker image
    if: ${{ needs.should-workflow-run.outputs.shouldrun == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get docker version
        id: docker_version
        run: >
          ls -la;
          action=$(cat action.yml);
          regex='docker:\/\/asyncapi\/github-action-for-cli:([0-9.]+)';
          [[ $action =~ $regex ]];
          action_version=${BASH_REMATCH[1]};
          echo "action_version=$action_version" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image and export
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./github-action/Dockerfile
          tags: asyncapi/github-action-for-cli:${{ steps.docker_version.outputs.action_version }}
          outputs: type=docker,dest=/tmp/asyncapi.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: asyncapi
          path: /tmp/asyncapi.tar
